import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BarChart3, BookOpenCheck, BrainCircuit, FileCheck2, Layers3, Library, PenLine } from "lucide-react";
import { IsiPageShell } from "@/components/isi/IsiPageShell";
import { IsiLinkCard, IsiPageHeader, IsiStat } from "@/components/isi/IsiUi";
import { getMsqeManifest, getMsqeOverview } from "@/lib/content/isi/msqe";
import { getIsiMsqePyqPracticeSets } from "@/lib/content/isi/pyqPractice";
import { getIsiMsqePyqResources } from "@/lib/content/isi/pyq-resources";
import { getIsiMsqeSolutions } from "@/lib/content/isi/solutions";

export const metadata: Metadata = { title: "ISI MSQE Intelligence Cockpit", description: "PEA, PEB, PYQ practice, Statstrive resources, and inference modules for ISI MSQE." };

export default function MsqeCockpitPage() {
  const overview = getMsqeOverview();
  const manifest = getMsqeManifest();
  const pyqSets = getIsiMsqePyqPracticeSets().filter((set) => set.paper === "PEA");
  const solutions = getIsiMsqeSolutions();
  const pyqResources = getIsiMsqePyqResources();
  const pyqQuestions = pyqSets.reduce((sum, set) => sum + set.questionCount, 0);

  return <IsiPageShell><section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_360px]"><IsiPageHeader eyebrow="ISI / MSQE" title="MSQE intelligence cockpit" description="A two-paper preparation system with PEA PYQ practice as the main student experience, plus PEB preview, Statstrive-generated booklets, and inference modules. Statstrive does not host third-party archive bundles." chips={["PEA PYQs live", "Free login tier", "In-app solutions", "Question-only PDFs"]} /><aside className="aurora-surface rounded-3xl p-5 shadow-[0_22px_75px_rgba(15,23,42,0.07)]"><p className="text-xs font-bold uppercase tracking-[0.17em]" style={{ color: "var(--aurora-cyan)" }}>Content layers</p><div className="mt-4 grid grid-cols-2 gap-3"><IsiStat label="PEA PYQs" value={String(pyqQuestions)} note="practice questions" /><IsiStat label="Practice years" value={String(pyqSets.length)} note="2022-2026" /><IsiStat label="Solution books" value={String(solutions.length)} note="resource layer" /><IsiStat label="Dev preview" value={String(overview.sampleQuestionCount)} note="sample items" /></div><p className="mt-4 text-xs leading-5" style={{ color: "var(--aurora-text-muted)" }}>{manifest.sourceInventory.note}</p></aside></div>
  <Link href="/exams/isi/msqe/pyqs/pea" className="aurora-glass aurora-card-hover aurora-focus-ring mt-10 flex flex-col gap-5 p-6 shadow-[0_24px_85px_rgba(14,165,233,0.1)] sm:flex-row sm:items-center"><span className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl text-white" style={{ background: "linear-gradient(135deg, var(--aurora-primary), var(--aurora-violet))", boxShadow: "var(--aurora-glow-md)" }}><BookOpenCheck size={23} /></span><span className="min-w-0 flex-1"><span className="block text-xs font-bold uppercase tracking-[0.16em]" style={{ color: "var(--aurora-primary)" }}>Primary student CTA</span><span className="mt-2 block text-2xl font-extrabold">PEA PYQ Practice</span><span className="mt-2 block text-sm leading-6" style={{ color: "var(--aurora-text-secondary)" }}>Year-wise PYQ sets, question-wise practice, in-app solution reveal, and question-only Statstrive booklets.</span></span><span className="inline-flex items-center gap-2 text-sm font-bold" style={{ color: "var(--aurora-primary)" }}>Open practice <ArrowRight size={15} /></span></Link>
  <div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><IsiLinkCard icon={PenLine} title="PEB descriptive paper" description="Development preview for multipart responses, long solutions, and answer structure. Real PEB booklets are pending." href="/exams/isi/msqe/peb" badge="Sample preview" /><IsiLinkCard icon={Layers3} title="Development practice preview" description="Combined sample items remain clearly separated from real PYQ sets." href="/exams/isi/msqe/practice" badge={`${overview.sampleQuestionCount} dev items`} /><IsiLinkCard icon={FileCheck2} title="PEA PYQ practice" description="Practice-first PYQ landing with year cards, interactive checking, and generated booklet downloads." href="/exams/isi/msqe/pyqs" badge={`${pyqResources.length} booklets`} /><IsiLinkCard icon={Library} title="Solutions resource vault" description="Statstrive-created solution PDF and TeX booklets. Not the main student CTA." href="/exams/isi/msqe/solutions" badge={`${solutions.length} booklets`} /><IsiLinkCard icon={BrainCircuit} title="Inference intelligence" description="Topic frequency, archetypes, traps, difficulty shifts, and PEA/PEB comparison modules." href="/exams/isi/msqe/inference" badge="Modules ready" /><IsiLinkCard icon={BarChart3} title="Reports and taxonomy" description="Deep-tagged CSV banks and inference reports were detected for a later validated import pass." badge="827 structured rows detected" /></div></section></IsiPageShell>;
}
