import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, CheckCircle2, MousePointerClick, Target } from "lucide-react";
import { IsiPageShell } from "@/components/isi/IsiPageShell";
import { IsiPageHeader, IsiStat } from "@/components/isi/IsiUi";
import { MsqeQuestionCard } from "@/components/isi/MsqeQuestionCard";
import { getMsqePeaQuestions, getMsqeTopicStats } from "@/lib/content/isi/msqe";

export const metadata: Metadata = { title: "MSQE PEA Objective Practice", description: "Objective and MCQ-focused practice architecture for ISI MSQE PEA." };
export default function MsqePeaPage() { const questions = getMsqePeaQuestions(); const topics = getMsqeTopicStats().filter((item) => item.peaCount > 0); return <IsiPageShell><section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_340px]"><IsiPageHeader eyebrow="MSQE / PEA" title="Objective paper intelligence" description="PEA is modeled as the objective recognition layer: options, fast concept identification, distractor awareness, and disciplined answer selection." chips={["MCQ-ready", "Option support", "Trap-analysis boundary"]} /><aside className="aurora-surface rounded-3xl p-5"><div className="grid grid-cols-2 gap-3"><IsiStat label="Dev questions" value={String(questions.length)} /><IsiStat label="Topics" value={String(topics.length)} /></div><div className="mt-4 space-y-3 text-sm"><Signal icon={MousePointerClick} text="Objective answer selection" /><Signal icon={Target} text="Concept and difficulty metadata" /><Signal icon={CheckCircle2} text="Answer reveal supported" /></div></aside></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{topics.map((topic) => <div key={topic.topic} className="aurora-glass p-5"><p className="text-xs font-bold uppercase tracking-[0.14em]" style={{ color: "var(--aurora-primary)" }}>{topic.topic}</p><p className="mt-3 text-3xl font-extrabold">{topic.peaCount}</p><p className="mt-1 text-xs" style={{ color: "var(--aurora-text-muted)" }}>development samples</p></div>)}</div><div className="mt-10 grid gap-5 md:grid-cols-2">{questions.map((question) => <MsqeQuestionCard key={question.id} question={question} />)}</div><Link href="/exams/isi/msqe/practice" className="aurora-button-primary aurora-focus-ring mt-8 inline-flex px-5 text-sm">Open combined practice <ArrowRight size={15} /></Link></section></IsiPageShell>; }
function Signal({ icon: Icon, text }: { icon: typeof Target; text: string }) { return <div className="flex items-center gap-3 rounded-2xl border bg-white/60 p-3" style={{ borderColor: "var(--aurora-border-soft)" }}><Icon size={16} style={{ color: "var(--aurora-primary)" }} /><span className="font-semibold">{text}</span></div>; }
