import type { Metadata } from "next";
import { Activity, BarChart3, BrainCircuit, GitCompareArrows, ScanSearch, TriangleAlert } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { IsiPageShell } from "@/components/isi/IsiPageShell";
import { IsiPageHeader } from "@/components/isi/IsiUi";
import { getMsqeInferenceSummary, getMsqeTopicStats } from "@/lib/content/isi/msqe";

export const metadata: Metadata = { title: "MSQE Inference Intelligence", description: "Topic, concept, archetype, trap, and difficulty intelligence modules for ISI MSQE." };
const icons: Record<string, LucideIcon> = { "topic-frequency": BarChart3, "deep-concepts": BrainCircuit, archetypes: ScanSearch, traps: TriangleAlert, difficulty: Activity, comparison: GitCompareArrows };
export default function MsqeInferencePage() { const modules = getMsqeInferenceSummary(); const topics = getMsqeTopicStats(); return <IsiPageShell><section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><IsiPageHeader eyebrow="MSQE / Inference" title="From question bank to exam intelligence." description="The inference layer is structured for topic incidence, deep concepts, repeated archetypes, traps, difficulty movement, and PEA/PEB comparison. Report modules are ready to accept verified metadata." chips={["Official-hierarchy boundary", "PEA / PEB comparison", "No unsupported predictions"]} /><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{modules.map((module) => { const Icon = icons[module.id] ?? BrainCircuit; return <article key={module.id} className="aurora-glass aurora-card-hover p-6"><div className="flex items-center justify-between"><span className="grid h-11 w-11 place-items-center rounded-xl text-white" style={{ background: "linear-gradient(135deg, var(--aurora-primary), var(--aurora-violet))" }}><Icon size={19} /></span><span className="aurora-badge">Report module ready</span></div><h2 className="mt-5 text-lg font-bold">{module.title}</h2><p className="mt-2 text-sm leading-7" style={{ color: "var(--aurora-text-secondary)" }}>{module.description}</p></article>; })}</div><div className="mt-10 rounded-3xl border bg-white/65 p-6" style={{ borderColor: "var(--aurora-border-soft)" }}><h2 className="text-lg font-bold">Current development taxonomy coverage</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{topics.map((topic) => <div key={topic.topic} className="rounded-2xl border bg-white/70 p-4" style={{ borderColor: "var(--aurora-border-soft)" }}><p className="font-bold">{topic.topic}</p><p className="mt-2 text-xs" style={{ color: "var(--aurora-text-muted)" }}>PEA {topic.peaCount} / PEB {topic.pebCount} development samples</p></div>)}</div></div></section></IsiPageShell>; }
