import type { Metadata } from "next";
import { BarChart3, Calculator, GraduationCap, Sigma } from "lucide-react";
import { IsiPageShell } from "@/components/isi/IsiPageShell";
import { IsiLinkCard, IsiPageHeader } from "@/components/isi/IsiUi";

export const metadata: Metadata = { title: "ISI Exam Intelligence", description: "Statstrive intelligence and practice vertical for ISI entrance programs." };

export default function IsiExamFamilyPage() {
  return <IsiPageShell><section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><IsiPageHeader eyebrow="Statstrive / ISI" title="ISI exam intelligence, built program by program." description="A dedicated research, practice, and inference vertical for ISI entrance programs. MSQE is active in Phase 1, with reusable content boundaries prepared for MStat and MMath." chips={["Multi-program architecture", "Structured local content", "Math-safe rendering"]} /><div className="mt-10 grid gap-5 lg:grid-cols-3"><IsiLinkCard icon={BarChart3} title="MSQE" description="Objective PEA and descriptive PEB practice, topic intelligence, PYQ staging, and inference modules." href="/exams/isi/msqe" badge="Active" /><IsiLinkCard icon={GraduationCap} title="MStat" description="Program boundary reserved for a future verified syllabus, source bank, and inference layer." badge="Research layer preparing" /><IsiLinkCard icon={Sigma} title="MMath" description="Program boundary reserved for future proof-heavy mathematics practice and source intelligence." badge="Coming next" /></div><div className="mt-8 rounded-3xl border bg-white/65 p-6 shadow-sm" style={{ borderColor: "var(--aurora-border-soft)" }}><div className="flex items-start gap-4"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-xl" style={{ background: "var(--aurora-background-soft)", color: "var(--aurora-primary)" }}><Calculator size={19} /></span><div><h2 className="text-lg font-bold">Source-first by design</h2><p className="mt-2 text-sm leading-7" style={{ color: "var(--aurora-text-secondary)" }}>Verified JSON, Markdown, text, or LaTeX feeds the website. PDFs remain source references and are not treated as direct rendering inputs.</p></div></div></div></section></IsiPageShell>;
}
