import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, FilePenLine, ListChecks, Workflow } from "lucide-react";
import { IsiPageShell } from "@/components/isi/IsiPageShell";
import { IsiPageHeader, IsiStat } from "@/components/isi/IsiUi";
import { MsqeQuestionCard } from "@/components/isi/MsqeQuestionCard";
import { getMsqePebQuestions, getMsqeTopicStats } from "@/lib/content/isi/msqe";

export const metadata: Metadata = { title: "MSQE PEB Descriptive Practice", description: "Descriptive and multipart practice architecture for ISI MSQE PEB." };
export default function MsqePebPage() { const questions = getMsqePebQuestions(); const topics = getMsqeTopicStats().filter((item) => item.pebCount > 0); return <IsiPageShell><section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8"><div className="grid gap-8 lg:grid-cols-[minmax(0,1fr)_340px]"><IsiPageHeader eyebrow="MSQE / PEB" title="Descriptive paper intelligence" description="PEB is modeled as the construction layer: multipart reasoning, derivation quality, economic interpretation, and readable answer structure." chips={["Long-form solutions", "Multipart-ready", "Marking notes"]} /><aside className="aurora-surface rounded-3xl p-5"><div className="grid grid-cols-2 gap-3"><IsiStat label="Dev questions" value={String(questions.length)} /><IsiStat label="Topics" value={String(topics.length)} /></div><div className="mt-4 space-y-3 text-sm"><Signal icon={FilePenLine} text="Written solution practice" /><Signal icon={Workflow} text="Step-by-step derivation" /><Signal icon={ListChecks} text="Answer-structure notes" /></div></aside></div><div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{topics.map((topic) => <div key={topic.topic} className="aurora-glass p-5"><p className="text-xs font-bold uppercase tracking-[0.14em]" style={{ color: "var(--aurora-violet)" }}>{topic.topic}</p><p className="mt-3 text-3xl font-extrabold">{topic.pebCount}</p><p className="mt-1 text-xs" style={{ color: "var(--aurora-text-muted)" }}>development samples</p></div>)}</div><div className="mt-10 grid gap-5 md:grid-cols-2">{questions.map((question) => <MsqeQuestionCard key={question.id} question={question} />)}</div><Link href="/exams/isi/msqe/practice" className="aurora-button-primary aurora-focus-ring mt-8 inline-flex px-5 text-sm">Open combined practice <ArrowRight size={15} /></Link></section></IsiPageShell>; }
function Signal({ icon: Icon, text }: { icon: typeof Workflow; text: string }) { return <div className="flex items-center gap-3 rounded-2xl border bg-white/60 p-3" style={{ borderColor: "var(--aurora-border-soft)" }}><Icon size={16} style={{ color: "var(--aurora-violet)" }} /><span className="font-semibold">{text}</span></div>; }
